CREATE TABLE savedPost (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    username VARCHAR(50) NOT NULL REFERENCES users(username) ON DELETE CASCADE,
    postid BIGINT REFERENCES posts(id) ON DELETE CASCADE
);